### ISSUE TITLE
Introducing React / Redux

### ISSUE THREAD

**Issue by tooxoot** [tooxoot/plotR#18]
Introducing react / redux to the Project will make the implementation of the different Interactions between view and model components significantly easier.

#### ToDos:
- [x] Introduce React project structure
- [x] Introduce a view Component showing the different drawable elements
  - [x] The view highlights the currently selected elements
- [x] Introducing a component that lists all elements.
  - [x] Selection via list component
  - [x] Toggle element's closed flag via list component
  - [x] Toggle element's filled flag via list component
- [x] Introducing a debug view that shows the original svg, the processed iput as svg, the clipped model as svg, the  hpgl output as formatted readable text.
- [x] Introducing a component to fill the selected elements with a line filling.
