### ISSUE TITLE
Process svg input

### ISSUE THREAD

**Issue by tooxoot** [tooxoot/plotR#5]
To get any svg input file ready for further processing it is necessary to:(https://github.com/tooxoot/plotR/tree/master/src/app/shared/svg-processor/svg.element.splitter.ts))~~

### TODOS:

  - [ ] Take a closer look on the different filling / stroke combinations
  - [ ] Add `GraphicsValues` to the model components (useful for filtering etc.)
  - [ ] Convert all arc like elements into polyline like `path` elements (see #2) 
  - [ ] Convert all shapes into polyline like sets of points
  - [ ] Handle the count of polyline points in converted curved elements dynamically depending on size / curvature 
  - [x] Handle transformations. (#17)
  
### Questions

1. Check relevance for inkscape / illustrator:
    1. What are stroke and filling combinations?
    2. Are there round rectangle corners? 
    3. Are there transformations?
 
### Restrictions
 - No conjoined path elements with multiple `M` commands (eg: `d="M 0 0 1 1 2 2 M 3 3 4 4 5 5"`)
-
